apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nodeaccess.fullname" . }}
  labels:
    {{- include "nodeaccess.labels" . | nindent 4 }}
data:
  APP_PORT_API: {{ .Values.api.port | quote }}
  APP_PORT_GATEWAY: {{ .Values.gateway.port | quote }}
  GUACD_HOST: {{ ternary (printf "%s-guacd" (include "nodeaccess.fullname" .)) "127.0.0.1" .Values.guacd.enabled | quote }}
  GUACD_PORT: {{ .Values.guacd.port | quote }}
  {{- range $key, $value := .Values.config }}
  {{- if ne (toString $value) "" }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
  {{- range $key, $value := .Values.extraEnv }}
  {{- if ne (toString $value) "" }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
