{{- if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nodeaccess.fullname" . }}-frontend
  labels:
    {{- include "nodeaccess.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        {{- include "nodeaccess.labels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      serviceAccountName: {{ include "nodeaccess.serviceAccountName" . }}
      automountServiceAccountToken: false
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          env:
            - name: API_UPSTREAM
              value: {{ printf "%s-api:%v" (include "nodeaccess.fullname" .) .Values.api.port | quote }}
            - name: GATEWAY_UPSTREAM
              value: {{ printf "%s-gateway:%v" (include "nodeaccess.fullname" .) .Values.gateway.port | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.port }}
          readinessProbe:
            httpGet: { path: /, port: http }
          livenessProbe:
            httpGet: { path: /, port: http }
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nodeaccess.fullname" . }}-frontend
spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: {{ .Values.frontend.port }}
      targetPort: http
{{- end }}
