CREATE TABLE `host_import_jobs` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `tenant_id` INTEGER NOT NULL,
  `actor_id` INTEGER NOT NULL,
  `preview_id` VARCHAR(36) NOT NULL,
  `source` VARCHAR(24) NOT NULL,
  `status` VARCHAR(24) NOT NULL DEFAULT 'PREVIEWED',
  `detected_hosts` INTEGER NOT NULL DEFAULT 0,
  `ready_hosts` INTEGER NOT NULL DEFAULT 0,
  `blocked_hosts` INTEGER NOT NULL DEFAULT 0,
  `created_hosts` INTEGER NOT NULL DEFAULT 0,
  `updated_hosts` INTEGER NOT NULL DEFAULT 0,
  `created_folders` INTEGER NOT NULL DEFAULT 0,
  `impact_json` LONGTEXT NULL,
  `snapshot_json` LONGTEXT NULL,
  `completed_at` DATETIME(3) NULL,
  `reverted_at` DATETIME(3) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  UNIQUE INDEX `host_import_jobs_preview_id_key`(`preview_id`),
  INDEX `host_import_jobs_tenant_created_idx`(`tenant_id`, `created_at`),
  INDEX `host_import_jobs_tenant_status_idx`(`tenant_id`, `status`, `created_at`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
