CREATE TABLE `ai_interactions` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `correlation_id` VARCHAR(36) NOT NULL,
  `tenant_id` INTEGER NOT NULL,
  `user_id` INTEGER NOT NULL,
  `channel` VARCHAR(32) NOT NULL,
  `purpose` VARCHAR(64) NOT NULL,
  `provider` VARCHAR(64) NOT NULL,
  `model` VARCHAR(191) NOT NULL,
  `routing_policy` VARCHAR(32) NOT NULL,
  `status` VARCHAR(24) NOT NULL,
  `host_id` INTEGER NULL,
  `session_id` INTEGER NULL,
  `ticket_key` VARCHAR(100) NULL,
  `context_categories` TEXT NULL,
  `context_chars` INTEGER NOT NULL DEFAULT 0,
  `tools` TEXT NULL,
  `redaction_count` INTEGER NOT NULL DEFAULT 0,
  `latency_ms` INTEGER NOT NULL DEFAULT 0,
  `input_tokens` INTEGER NOT NULL DEFAULT 0,
  `output_tokens` INTEGER NOT NULL DEFAULT 0,
  `error_kind` VARCHAR(32) NULL,
  `retention_until` DATETIME(3) NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE INDEX `ai_interactions_correlation_id_key` (`correlation_id`),
  INDEX `ai_interactions_tenant_id_created_at_idx` (`tenant_id`, `created_at`),
  INDEX `ai_interactions_tenant_id_channel_created_at_idx` (`tenant_id`, `channel`, `created_at`),
  INDEX `ai_interactions_retention_until_idx` (`retention_until`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
